[package]
name = "exam_q6_22T3"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "exam_q6"
path = "src/main.rs"

[lib]
name = "exam_q6_lib"
path = "src/lib.rs"

[dependencies]
