[package]
name = "my_epic_binary"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
my_slick_lib = { path = "../my_slick_lib" }
rand = "0.8.5"
